---
title: "R Notebook"
output: html_notebook
---

Is there a relationship between the size of the population living near to a volcano and the nature of that volcano?

for the highest populated volcanic areas…

how intense are the volcanoes

how often do they blow

how recent

```{r}
# Count number of eruptions and everage VEI per volcano
volcano_counts <- eruptions %>% 
  drop_na(vei) %>% 
  group_by(volcano_number) %>% 
  summarise((no_eruptions = n()), ave_vei = mean(vei))
```

```{r}
# Merge counts into the volcano database
volcano_counts <- left_join(volcanoes, volcano_counts, by = "volcano_number")
```

```{r}
# Remove the unknown eruptions
volcano_counts <- volcano_counts %>% 
  filter(last_eruption_year != "Unknown")
```

```{r}
summary(volcano_counts)
```

There are still 132 NAs in the count and VEI fields so I will drop those too

```{r}
volcano_counts <- volcano_counts %>% 
  drop_na(ave_vei) 
```

```{r}
volcano_counts <- volcano_counts %>% 
  mutate(last_eruption_year= as.numeric(last_eruption_year))
```

```{r}
volcano_counts %>% 
  ggplot()+
    geom_point(aes(x=last_eruption_year, y = population_within_5_km)) +
      labs(
      x = "Year of last eruption",
      y = "Population living within 5km",
      title = "Population living within 5km of a Volcano",
      subtitle = "and Year the Volcano last erupted"
      ) 
```

```{r}
volcano_counts %>% 
  filter(last_eruption_year > 0) %>% 
  ggplot()+
    geom_point(aes(x=last_eruption_year, y = population_within_5_km)) +
      labs(
      x = "Year of last eruption",
      y = "Population living within 5km",
      title = "Population living within 5km of a Volcano",
      subtitle = "and Year the Volcano last erupted (since Year 0)"
      ) 
```

```{r}
volcano_counts %>% 
  filter(last_eruption_year > 1900) %>% 
  ggplot()+
    geom_point(aes(x=last_eruption_year, y = population_within_5_km)) +
      labs(
      x = "Year of last eruption",
      y = "Population living within 5km",
      title = "Population living within 5km of a Volcano",
      subtitle = "and Year the Volcano last erupted (since Year 0)"
      ) 
```

```{r}
volcano_counts %>% 
  filter(last_eruption_year > 1900) %>% 
  filter(population_within_5_km<1000000) %>% 
  ggplot()+
    geom_point(aes(x=last_eruption_year, y = population_within_5_km)) +
      labs(
      x = "Year of last eruption",
      y = "Population living within 5km",
      title = "Population living within 5km of a Volcano",
      subtitle = "and Year the Volcano last erupted (since Year 0)"
      ) 
```

