---
title: "Import Data for Analysis"
output: html_notebook
---

```{r}
library(tidyverse)
library(here)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(ggplot2)
library(rgeos)
```

# Import Datasets
```{r}
eruptions <- read_csv(here("data/clean_data/eruptions.csv"))
commented_events <- read_csv(here("data/clean_data/commented_events.csv"))
events <- read_csv(here("data/clean_data/events.csv"))
sulfur <- read_csv(here("data/clean_data/sulfur.csv"))
tree_rings <- read_csv(here("data/clean_data/tree_rings.csv"))
volcanoes <- read_csv(here("data/clean_data/volcanoes.csv"))
vei_scale <- read_csv(here("data/clean_data/vei_scale.csv"))
volcano_deaths <- read_csv(here("data/clean_data/volcano_deaths.csv"))
```

```{r}
# import tectonic plates 
st_read("https://raw.githubusercontent.com/fraxen/tectonicplates/master/GeoJSON/PB2002_plates.json") -> tectonic_plates
```

```{r}
# Change longitude and latitude to numeric
volcanoes <- volcanoes %>% 
  mutate_at(
    vars(
        longitude, latitude),
    as.numeric
    ) 
```

```{r}
# tidy primary volcano type in volcanoes table
volcanoes <- volcanoes %>% 
  mutate(primary_volcano_type = 
           replace(primary_volcano_type, 
                   primary_volcano_type == "Lava cone(es)", "Lava cone")) %>% 
  mutate(primary_volcano_type = 
           replace(primary_volcano_type, 
                   primary_volcano_type == "Lava cone(s)", "Lava cone")) %>% 
  mutate(primary_volcano_type = 
           replace(primary_volcano_type, 
                   primary_volcano_type == "Lava cone(es)", "Lava cone")) %>% 
  mutate(primary_volcano_type = 
           replace(primary_volcano_type, 
                   primary_volcano_type == "Caldera(s)", "Caldera")) %>% 
  mutate(primary_volcano_type = 
           replace(primary_volcano_type, 
                   primary_volcano_type == "Lava dome(s)", "Lava dome")) %>% 
  mutate(primary_volcano_type = 
           replace(primary_volcano_type, 
                   primary_volcano_type == "Pyroclastic cone(s)", "Pyroclastic cone")) %>% 
  mutate(primary_volcano_type = 
           replace(primary_volcano_type, 
                   primary_volcano_type == "Shield(s)", "Shield")) %>% 
  mutate(primary_volcano_type = 
           replace(primary_volcano_type, 
                   primary_volcano_type == "Stratovolcano?", "Stratovolcano")) %>% 
  mutate(primary_volcano_type = 
           replace(primary_volcano_type, 
                   primary_volcano_type == "Stratovolcano(es)", "Stratovolcano")) %>% 
  mutate(primary_volcano_type = 
           replace(primary_volcano_type, 
                   primary_volcano_type == "Tuff cone(s)", "Tuff cone")) %>% 
    mutate(primary_volcano_type = 
           replace(primary_volcano_type, 
                   primary_volcano_type == "Complex(es)", "Complex")) 
```

# Manipulate datasets
```{r}
# Count number of eruptions by VEI
eruptions %>% 
  group_by(vei) %>% 
  summarise(count = n())
```

```{r}
# Add the volcano detail onto the eruption database
eruptions_volc <- left_join(eruptions, volcanoes, by = "volcano_name")
```

```{r}
# Remove duplicate columns
eruptions_volc = 
  select(eruptions_volc, -volcano_number.y, -latitude.y, -longitude.y)
```

```{r}
# Rename columns
eruptions_volc = 
rename(eruptions_volc, volcano_number = volcano_number.x)

eruptions_volc = 
rename(eruptions_volc, latitude = latitude.x)

eruptions_volc = 
rename(eruptions_volc, longitude = longitude.x)

```

```{r}
# Create dataset with just recorded vei values
eruptions_vei <- eruptions_volc %>% drop_na(vei)
```

```{r}
# Count number of eruptions by VEI
count_vei <- eruptions_vei %>% 
  group_by(vei) %>% 
  summarise(count = n())
count_vei
```

```{r}
# change the VEI to a factor
eruptions_vei <- eruptions_vei %>% 
  mutate(vei = as.factor(vei))
```

```{r}
ggplot(eruptions_vei, aes(x=vei, fill = vei)) +  
  geom_bar( ) +
  scale_fill_manual(values =  c("0" = "khaki", "1" = "gold1", "2" = "darkgoldenrod2",
          "3" = "darkorange2", "4" = "firebrick1", "5" = "firebrick", "6" = "firebrick4",
          "7" = "black")) +
    labs(
      x = "VEI - Volcanic Explosivity Index",
      y = "Number of Eruptions",
      title = "Number of Eruptions by VEI"
      ) 
```

```{r}
eruption_count <- eruptions_vei %>% 
  group_by(volcano_number) %>% 
  summarise(e_count=n()) %>% 
  arrange(desc(e_count))
```

```{r}
# Add in the volcano information to the eruption counts
eruption_count <- left_join(eruption_count, volcanoes, by = "volcano_number")
```

```{r}
count_of_counts <- eruption_count %>% 
  group_by(e_count) %>% 
  summarise(no_volc =n())
```


```{r}
volcanoes_over_100 <- eruption_count %>% 
  filter(e_count > 100)
```

Can we look at which volcanoes have been active recently - so number of eruptions and recency of eruptions.

```{r}
# Drop NAs from eruption count table
eruption_count <- eruption_count %>% drop_na(last_eruption_year)
```

```{r}
# Drop Unknowns from eruption count table
eruption_count <- eruption_count %>% 
  filter(last_eruption_year != "Unknown")
```

```{r}
# Convert the last eruption year to numeric
eruption_count$last_eruption_year <- 
  as.numeric(as.character(eruption_count$last_eruption_year))
```

```{r}
# Create new column showing years since last eruption
eruption_count <- eruption_count %>% 
  mutate(years_since = 2020 - last_eruption_year)
eruption_count
```

```{r}
# Number of deaths already known
volcano_deaths <- left_join(volcano_deaths, volcanoes, by = "volcano_name")
```

```{r}
volcano_deaths <- volcano_deaths %>% 
  drop_na(volcano_number)
```

```{r}
volcano_deaths = 
  select(volcano_deaths, -country.y)
```

```{r}
volcano_deaths = 
  rename(volcano_deaths, country = country.x)
```

```{r}
# Find volcanoes with a known last eruption date
volc_known_eruption <- volcanoes %>% 
 filter(last_eruption_year != "Unknown") 
```

```{r}
volc_known_eruption <- volc_known_eruption %>% 
  mutate(last_eruption_year = as.numeric(last_eruption_year))
```

```{r}
popn_1mn_plus <- volcanoes %>% 
  filter(population_within_10_km>1000000) %>% 
  select("volcano_name", "country", "population_within_10_km", "latitude", "longitude")
```

```{r}
world <- ne_countries(scale = "medium", returnclass = "sf")
class(world)
```

```{r}
# filter the data to Indonesia
country_indonesia <- world %>%
  filter(name == "Indonesia")
```


```{r}
# Let's find all Indonesian volcanoes
indonesia_vol <- volcanoes %>% 
  filter(country == "Indonesia")
```

```{r}
# Let's find all Tambora
tambora <- volcanoes %>% 
  filter(volcano_name == "Tambora")
```


```{r}
ggplot(data = world) +
    geom_sf(aes(fill = pop_est)) +
    scale_fill_viridis_c(option = "plasma", trans = "sqrt")
```


```{r}
# Adding the VEI of eruptions onto the death table
eruptions_vei2 <- eruptions_vei %>% 
  select(volcano_name, start_year, vei)


volcano_deaths <- left_join(volcano_deaths, eruptions_vei2, 
          by = c("volcano_name" = "volcano_name",
                 "year" = "start_year"))

```



