---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(rgeos)
library(ggplot2)
```

```{r}
ggplot(data = world) +
    geom_sf(aes(fill = pop_est)) +
    scale_fill_viridis_c(option = "plasma", trans = "sqrt")
```

```{r}
# filter the data to Indonesia
country_indonesia <- world %>%
  filter(name == "Indonesia")
```

```{r}
# Let's find all Indonesian volcanoes
indonesia_vol <- volcanoes %>% 
  filter(country == "Indonesia")
```

```{r}
# Base map of Indonesia 
ggplot(country_indonesia) + 
  geom_sf() + 
  ggtitle("Map of Indonesia and its Volcanoes") + 
    xlab("Longitude") + ylab("Latitude") +
  geom_point(data = indonesia_vol, 
             aes(x= longitude,  y = latitude),
             size = 2, shape = 24, colour = "darkred", fill = "darkred")
```

```{r}
# Base map of Indonesia 
ggplot(country_indonesia) + 
  geom_sf() + 
  ggtitle("Map of Indonesia and its Volcanoes") + 
    xlab("Longitude") + ylab("Latitude") +
  geom_point(data = indonesia_vol %>% filter(volcano_name == "Tambora"), 
             aes(x= longitude,  y = latitude),
             size = 2, shape = 24, colour = "darkred", fill = "darkred") +
  geom_polygon(data = myCircles, aes(lon, lat, group = ID), color = "red", alpha = 0)
```

```{r}
  geom_point(data = . %>% filter(continent == "Asia"), 
             size=5, color="gray")
```

Java is considered to be the most populated island in the world with about 152 million people living on the island, neighbouring Sumatra is the fourth most populous island housing 58 million people. (Source: https://wonderingmaps.com/indonesia-population-density/)

```{r}
library(ggplot2)
library(ggmap)
data = data.frame(
    ID = as.numeric(c(1:8)),
    longitude = as.numeric(c(-8.25)),
    latitude = as.numeric(c(118))
)

#################################################################################
# create circles data frame from the centres data frame
make_circles <- function(centers, radius, nPoints = 100){
    # centres: the data frame of centres with ID
    # radius: radius measured in kilometre
    #
    meanLat <- mean(centers$latitude)
    # length per longitude changes with latitude, so need correction
    radiusLon <- radius /111 / cos(meanLat/57.3) 
    radiusLat <- radius / 111
    circleDF <- data.frame(ID = rep(centers$ID, each = nPoints))
    angle <- seq(0,2*pi,length.out = nPoints)

    circleDF$lon <- unlist(lapply(centers$longitude, function(x) x + radiusLon * cos(angle)))
    circleDF$lat <- unlist(lapply(centers$latitude, function(x) x + radiusLat * sin(angle)))
    return(circleDF)
}

# here is the data frame for all circles
myCircles <- make_circles(data, 0.45)
##################################################################################


island = get_map(location = c(lon = -63.247593, lat = 17.631598), zoom = 13)
islandMap = ggmap(island, extent = "panel", legend = "bottomright")
RL = geom_point(aes(x = longitude, y = latitude), data = data, color = "#ff0000")
islandMap + RL + 
    scale_x_continuous(limits = c(-63.280, -63.21), expand = c(0, 0)) + 
    scale_y_continuous(limits = c(17.605, 17.66), expand = c(0, 0)) +
    ########### add circles
    geom_polygon(data = myCircles, aes(lon, lat, group = ID), color = "red", alpha = 0)
Share
```

