---
title: "Project Plan"
output: 
  html_document:
    number_sections: true
---

# Background

> A volcano is a rupture in the crust of a planetary-mass object, such as Earth, that allows hot lava, volcanic ash, and gases to escape from a magma chamber below the surface.
>
> Earth's volcanoes occur because its crust is broken into 17 major, rigid tectonic plates that float on a hotter, softer layer in its mantle. Therefore, on Earth, volcanoes are generally found where tectonic plates are diverging or converging, and most are found underwater.
>
> Erupting volcanoes can pose many hazards, not only in the immediate vicinity of the eruption. One such hazard is that volcanic ash can be a threat to aircraft, in particular those with jet engines where ash particles can be melted by the high operating temperature; the melted particles then adhere to the turbine blades and alter their shape, disrupting the operation of the turbine. Large eruptions can affect temperature as ash and droplets of sulfuric acid obscure the sun and cool the Earth's lower atmosphere (or troposphere); however, they also absorb heat radiated from the Earth, thereby warming the upper atmosphere (or stratosphere). Historically, volcanic winters have caused catastrophic famines.
>
> Wikipedia

# Questions

We all know what a volcano is but how do we really understand about them? Using datasets originally created as part of Tidy Tuesday (A weekly data project aimed at the R ecosystem) I want to learn more about them focusing on three questions:

1.  Where are volcanic eruptions likely to occur?

    -   tectonic plates

    -   elevation

2.  Is there a relationship between the size of the population living near to a volcano and the nature of that volcano?

    -   for the highest populated volcanic areas...

    -   how intense are the volcanoes

    -   how often do they blow

    -   how recent

3.  Which type of volcanoes have the highest VEI?

    -   What are the characteristics

# Method

-   Consider if I need additional datasets besides the five provided for the Tidy Tuesday project.

-   Import and clean datasets

-   Join the datasets if appropriate

-   EDA - look at what the data shows us

-   Use hypothesis testing to answer question 1

-   Investigate which volcanoes have a large, local population

-   Identify reasons for proximity to volcanoes.

# Project Plan

+-------------+------------------------------+------------------------------------+
| Day         | Activity                     | Notes                              |
+=============+==============================+====================================+
| Tuesday     | Produce Project Plan         |                                    |
+-------------+------------------------------+------------------------------------+
|             | Get Sign Off                 |                                    |
+-------------+------------------------------+------------------------------------+
|             | Import Datasets              |                                    |
+-------------+------------------------------+------------------------------------+
|             | Clean Datasets               |                                    |
+-------------+------------------------------+------------------------------------+
|             | Begin EDA                    |                                    |
+-------------+------------------------------+------------------------------------+
| Wednesday   | Continue EDA                 |                                    |
+-------------+------------------------------+------------------------------------+
|             | Mapping                      |                                    |
+-------------+------------------------------+------------------------------------+
| Thursday    | Hypothesis Testing           |                                    |
+-------------+------------------------------+------------------------------------+
| Friday      | Hypothesis Testing           |                                    |
+-------------+------------------------------+------------------------------------+
|             | Continue Mapping as required |                                    |
+-------------+------------------------------+------------------------------------+
| Weekend     | Consolidate Findings         |                                    |
+-------------+------------------------------+------------------------------------+
| Monday      | Finalise Analysis            |                                    |
+-------------+------------------------------+------------------------------------+
| Tuesday     | Complete Report/README       |                                    |
+-------------+------------------------------+------------------------------------+
|             | Write Presentation           |                                    |
+-------------+------------------------------+------------------------------------+
| Wednesday   | Presentation day             |                                    |
+-------------+------------------------------+------------------------------------+
